version: "3"

services:
  gemini-predict-server:
    image: gemini-predict-server
    environment:
      - AUTH_KEY="your-authen-key"
    ports:
      - "3000:443"
    container_name: gemini-predict-server
    restart: unless-stopped
